services:
  - type: web
    name: course-recommendation
    env: python
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/firebase_config.json
    secretFiles:
      - name: firebase_config.json
        mountPath: /etc/secrets/firebase_config.json
